using FluentMigrator;

namespace AdvanceCRM.Migrations.DefaultDB
{
    [Migration(20251213093900)]
    public class DefaultDB_20251213_093900_DemandayEmailTeam : Migration
    {
        public override void Up()
        {
            Create.Table("DemandayEnquiry")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayEnquiry_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayTeamLeader")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("DemandayEnquiryID").AsInt32().Nullable().ForeignKey("FK_DemandayTeamLeader_DemandayEnquiryId", "dbo", "DemandayEnquiry", "Id")
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("AddressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeamLeader_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayQuality")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayQuality_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayMIS")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayMIS_OwnerId_UserId", "dbo", "Users", "UserId");


            Create.Table("DemandayContacts")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Domain").AsString(100).Nullable()
                .WithColumn("Job_Level").AsString(100).Nullable()
                .WithColumn("Job_Function_Role").AsString(200).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("Continents").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("ProspectURL").AsString(100).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayContacts_OwnerId_UserId", "dbo", "Users", "UserId");


            Create.Table("EnquiryContacts")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_EnquiryContacts_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayVerification")
                    .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                    .WithColumn("SrNo").AsInt32().Nullable()
                    .WithColumn("Agent Name").AsString(200).Nullable()
                    .WithColumn("CDQA Comments").AsString(150).Nullable()
                    .WithColumn("CampaignID").AsInt32().Nullable()
                    .WithColumn("Company Name").AsString(200).Nullable()
                    .WithColumn("FirstName").AsString(100).Nullable()
                    .WithColumn("LastName").AsString(100).Nullable()
                    .WithColumn("Title").AsString(100).Nullable()
                    .WithColumn("Email").AsString(200).Nullable()
                    .WithColumn("WorkPhone").AsString(50).Nullable()
                    .WithColumn("Alternate_01").AsString(50).Nullable()
                    .WithColumn("Alternate_02").AsString(50).Nullable()
                    .WithColumn("ProfileLink").AsString(300).Nullable()
                    .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayVerification_OwnerId_UserId", "dbo", "Users", "UserId");
        }

        public override void Down()
        {
            Delete.Table("DemandayEnquiry");
            Delete.Table("DemandayTeamLeader");
            Delete.Table("DemandayQuality");
            Delete.Table("DemandayMIS");
            Delete.Table("DemandayContacts");
            Delete.Table("EnquiryContacts");
            Delete.Table("DemandayVerification");
        }
    }
}
