using FluentMigrator;

namespace AdvanceCRM.Migrations.DefaultDB
{
    [Migration(20251213093600)]
    public class DefaultDB_20251213_093600_DemandayTeleMarketingTeam : Migration
    {
        public override void Up()
        {
            Create.Table("DemandayTeleMarketingEnquiry")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("AddressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingEnquiry_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayTeleMarketingTeamLeader")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("TeleMarketingEnquiryID").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingTeamLeader_EnquiryId", "dbo", "DemandayTeleMarketingEnquiry", "Id")
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("AddressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingTeamLeader_OwnerId_UserId", "dbo", "Users", "UserId");

            Create.Table("DemandayTeleMarketingQualilty")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("AddressLink").AsString(300).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingQualilty_OwnerId_UserId", "dbo", "Users", "UserId");


            Create.Table("DemandayTeleMarketingMIS")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingMIS_OwnerId_UserId", "dbo", "Users", "UserId");


            Create.Table("DemandayTeleMarketingContacts")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("AgentsName").AsString(100).Nullable()
                .WithColumn("TlName").AsString(100).Nullable()
                .WithColumn("CampaignId").AsString(100).Nullable()
                .WithColumn("CompanyName").AsString(200).Nullable()
                .WithColumn("FirstName").AsString(100).Nullable()
                .WithColumn("LastName").AsString(100).Nullable()
                .WithColumn("Title").AsString(150).Nullable()
                .WithColumn("Email").AsString(200).Nullable()
                .WithColumn("WorkPhone").AsString(50).Nullable()
                .WithColumn("AlternativeNumber").AsString(50).Nullable()
                .WithColumn("Street").AsString(200).Nullable()
                .WithColumn("City").AsString(100).Nullable()
                .WithColumn("State").AsString(100).Nullable()
                .WithColumn("ZipCode").AsString(20).Nullable()
                .WithColumn("Country").AsString(100).Nullable()
                .WithColumn("CompanyEmployeeSize").AsInt32().Nullable()
                .WithColumn("Industry").AsString(100).Nullable()
                .WithColumn("Revenue").AsDecimal(18, 2).Nullable()
                .WithColumn("ProfileLink").AsString(300).Nullable()
                .WithColumn("CompanyLink").AsString(300).Nullable()
                .WithColumn("RevenueLink").AsString(300).Nullable()
                .WithColumn("EmailFormat").AsString(100).Nullable()
                .WithColumn("AdressLink").AsString(300).Nullable()
                .WithColumn("Tenurity").AsString(100).Nullable()
                .WithColumn("Code").AsString(100).Nullable()
                .WithColumn("Link").AsString(300).Nullable()
                .WithColumn("Md5").AsString(64).Nullable()
                .WithColumn("SLOT").AsString(100).Nullable()
                .WithColumn("PrimaryReason").AsString(200).Nullable()
                .WithColumn("Category").AsString(100).Nullable()
                .WithColumn("Comments").AsString(2000).Nullable()
                .WithColumn("QaStatus").AsString(100).Nullable()
                .WithColumn("DeliveryStatus").AsString(100).Nullable()
                .WithColumn("AgentName").AsString(100).Nullable()
                .WithColumn("QaName").AsString(100).Nullable()
                .WithColumn("CallDate").AsDateTime().Nullable()
                .WithColumn("DateAudited").AsDateTime().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("Source").AsString(100).Nullable()
                .WithColumn("VerificationMode").AsString(100).Nullable()
                .WithColumn("Asset1").AsString(200).Nullable()
                .WithColumn("Asset2").AsString(200).Nullable()
                .WithColumn("Domain").AsString(100).Nullable()
                .WithColumn("Job_Level").AsString(100).Nullable()
                .WithColumn("Job_Function_Role").AsString(200).Nullable()
                .WithColumn("Continents").AsString(100).Nullable()
                .WithColumn("ProspectURL").AsString(100).Nullable()
                .WithColumn("OwnerId").AsInt32().Nullable().ForeignKey("FK_DemandayTeleMarketingContacts_OwnerId_UserId", "dbo", "Users", "UserId");

        }

        public override void Down()
        {
            Delete.Table("DemandayTeleMarketingEnquiry");
            Delete.Table("DemandayTeleMarketingTeamLeader");
            Delete.Table("DemandayTeleMarketingQualilty");
            Delete.Table("DemandayTeleMarketingMIS");
            Delete.Table("DemandayTeleMarketingContacts");
        }
    }
}
