[assembly: Serenity.ComponentModel.RegisterPermissionKey("Sales:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Sales:Re-open Sales")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Challan:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Challan:Re-open Challan")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Purchase:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Purchase:Re-open Purchase")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("PurchaseOrder:Re-open PurchaseOrder")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Attendance:Can Approve")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Move to Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Re-open Enquiry")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Move to Invoice")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Move to Proforma")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Re-open Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Move to Invoice")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Re-open Proforma")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("CMS:Move to Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("CMS:Re-open CMS")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("AMC:Re-open AMC")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Products:StockAlert")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Attendance")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Enquiry")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Inventory")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Accounting")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("IVR:Click To Call")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Toolkit:VerifySheets")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("MasterSupression:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("ClientSupression:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayCompetitor:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandaySpecs:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("TalCampaign:Import")]

// Demanday sub-modules: Import / Export permissions
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayContacts:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayContacts:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayEnquiry:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayEnquiry:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayMIS:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayMIS:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayQuality:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayQuality:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeamLeader:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeamLeader:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingContacts:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingContacts:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingEnquiry:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingEnquiry:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingMIS:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingMIS:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingQualilty:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingQualilty:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingTeamLeader:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayTeleMarketingTeamLeader:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayVerification:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayVerification:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("EnquiryContacts:Import")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("EnquiryContacts:Export")]
// Toolkit sub-modules: Export permissions (Import keys already registered above)
[assembly: Serenity.ComponentModel.RegisterPermissionKey("TalCampaign:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("ClientSupression:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandayCompetitor:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("DemandaySpecs:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("MasterSupression:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("OpenCampaign:Export")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("OpenCampaign:Import")]
